openapi: '3.0.2'
info:
  title: Dokumentasi API User
  version: '1.0'
servers:
  - url: http://localhost:3000/api/v1/

paths:
  /users:
    get:
      tags:
      - user
      description: 'View All User'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: object
                properties:
                  id:
                    type: integer
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                  phoneNumber:
                    type: string
                  address:
                    type: string
                  password:
                    type: string
                  isAdmin:
                    type: boolean
                  image:
                    type: string
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
              examples:
                example Output:
                  value:
                    id: 1
                    firstName: Tono
                    lastName: Budiman
                    email: tonobudiman@gmail.com
                    phoneNumber: 082247514553
                    address: Jl.langka No.2 Bandung
                    isAdmin: FALSE
                    image: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fjakarta&psig=AOvVaw2kIMKA9p_ctpDg1xaqtj3e&ust=1709635653771000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCLjy65-32oQDFQAAAAAdAAAAABAE
                    createdAt : 20-10-2024
                    updatedAt: 20-10-2024
        '400':
          description: Bad Request
        '404':
          description: Not Found
  /users/delete/:id:
    delete:
      tags:
      - user
      description: 'View Detail User By ID'
      parameters: 
      - name: id
        in: path
        description: id of the user to retrieve
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
        '400':
          description: Eror or Invalid request
        '404':
          description: id not found
  /update/:id:
    put:
      tags:
      - user
      description: ''
      parameters: 
      - name: id
        in: path
        description: id of the user to retrieve
        required: true
        schema:
          type: integer
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - firstName
                - lastName
                - email
                - phoneNumber
                - address
                - password
                - isAdmin
                - image
              properties:
                id:
                  type: integer
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  format: email
                phoneNumber:
                  type: string
                address:
                  type: string
                password:
                  type: string
                  format: password
                isAdmin:
                  type: boolean
                image:
                  type: string
                  
      responses:
        '200':
          description: OK
        '400':
          description: Eror or Invalid request
        '404':
          description: id not found
  /detail/:id:
    get:
      tags:
      - user
      description: ''
      parameters: 
      - name: id
        in: path
        description: id of the user to retrieve
        required: true
        schema:
          type: integer 
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                type: object
                properties:
                  id:
                    type: integer
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                  phoneNumber:
                    type: string
                  address:
                    type: string
                  password:
                    type: string
                  isAdmin:
                    type: boolean
                  image:
                    type: string
                  createdAt:
                    type: string
                  updatedAt:
                    type: string
              examples:
                example Output:
                  value:
                    id: 1
                    firstName: Tono
                    lastName: Budiman
                    email: tonobudiman@gmail.com
                    phoneNumber: 082247514553
                    address: Jl.langka No.2 Bandung
                    isAdmin: FALSE
                    image: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fphotos%2Fjakarta&psig=AOvVaw2kIMKA9p_ctpDg1xaqtj3e&ust=1709635653771000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCLjy65-32oQDFQAAAAAdAAAAABAE
                    createdAt : 20-10-2024
                    updatedAt: 20-10-2024
        '400':
          description: Eror or Invalid request
        '404':
          description: id not found


 